services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    restart: always
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend:/app
