version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:80"
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./backend:/app
